<?php

namespace AppBundle\Repository;

/**
 * stateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stateRepository extends \Doctrine\ORM\EntityRepository
{
}
